### ISSUE TITLE
Find x,y,z coordinates of satellite given epoch

### ISSUE THREAD

**Issue by cassova** [lcx366/SLRfield#2]
Hi.

Thanks for this package!  Can this be used to find/predict (past or future) the x,y,z coordinates of a satellite using the ILRS data for a given satellite and epoch?

Thanks,
Nicholas

**Comment by lcx366** [comment]
Do you mean to use ILRS laser ranging data to accurately determine the orbit of the satellite, calculate the target's state (position and velocity) and other dynamic parameters, etc., and then do the orbit extrapolation? I am implementing this part of the function, because it involves a large number of perturbation models and measurement models, so it will take at least a year to complete.

**Comment by cassova** [comment]
Hi, I think I figured out that ILRS datasets already provide the x,y,z coordinates at specific epochs which was enough for me.  Sorry, I should have closed this.  Will do so now.
